### ISSUE TITLE
thumbnail is not loading

### ISSUE THREAD

**Issue by ajayrai1980** [Tarnadas/cemu-smmdb#2]
my courses thumbnail and courses online both thumbnail is not showing.
i am using amd graphic card latest driver.

**Comment by Tarnadas** [comment]
It's an issue of Cemu, not the website nor the save file editor.

Cemu 1.9.1 fixes this, but it's not working with AMD card, so you would have to wait until that is working. Until then you can use the thumbnail upload function on the website. It will create working thumbnails for your courses and you can redownload them as well to get a working thumbnail, however every time you save your course, it will overwrite that working thumbnail

**Comment by ajayrai1980** [comment]
Thumbnail is showing in cemu but it is not showing in save file editor. i am using cemu 1.7.5. I  was trying to download some levels but thumbnail is missing every where, but in older version of this client save file editor thumbnail is working fine but it is not compatible with the new site.

**Comment by mariomadproductions** [comment]
I'm getting this issue as well.

**Comment by andot** [comment]
I'm getting this issue, too.

**Comment by ajayrai1980** [comment]
guys there is nothing wrong with it just copy the game folder and cemu smmdb folder to the desktop and run this cemu-smmdb app as admin it will start working and first pls download the latest cemu version.

**Comment by Tarnadas** [comment]
Sorry I'm kind of busy with Net64 development.

Does running the program as admin make a difference?

**Comment by alemangioni** [comment]
I solve it, it was a path problem. If your path is longer than 256 won't show the images. I recommend moving the Cemu and it's games folder to the C:\ Directory. Something like C:\Cemu.

I used to have it at my Desktop so it had the long path (also I was using USB loader so it had longer path).
C:\Users\yourLongUserName\Desktop\AllCemuVersions\example-Cemu 1.9.6\Cemu\someDirectoriesICantRemember\games\yourLongIDNumber\yourSavesFiles\blablabla\yourCourses\CourseID\the***imageThatCantBeLoadedBecauseThisPathIsWayTooLong

**Comment by ajayrai1980** [comment]
yes it works well when all the folders are in c directory.
