### ISSUE TITLE
Save file locations don't seem to be compatible with newer versions of cemu

### ISSUE THREAD

**Issue by cbartondock** [Tarnadas/cemu-smmdb#3]
Hi,

Essentially the issue is that the cemu team has altered where it puts save files for games; it used to be

/path/to/cemu/mlc01/emulatorSave/fullgameid

and now its

/path/to/cemu/mlc01/usr/save/0050000/halfgameid 

When I try to set the path as above in SSMDB it doesn't recognize the save files. I suspect the issue is that whereas before SMM save files were stored in emulatorSave/00500001018dc0 they are now stored in /usr/save/0050000/1018dc0

Cemu did this so that game saves would be stored separately from system app stuff / dlc (which is now under the 0050010 folder).

Anyway I think this should be an easy fix!

**Comment by 2M0rr0w** [comment]
Same issue here

**Comment by majortriad** [comment]
Fyi, setting the save file to mlc01\usr\save\00050000\1018dd00\user\80000001\ works.
