### ISSUE TITLE
adds _reorder to the end of folder names and corrupts courses

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [Tarnadas/cemu-smmdb#4]
i have to keep renaming the folders to uncorrupt them
![image](https://user-images.githubusercontent.com/29156241/53895003-ed220080-3fe5-11e9-81ce-4aa73dcc1a19.png)

**Comment by ACKREIK** [comment]
(so did you ever find a fix to this)

**Comment by MacaylaMarvelous81** [comment]
I don't remember, but I think I came to the conclusion that cemu-smmdb was not the culprit of this problem.
